<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>system_config</name>
  <version>2.0.0</version>
  <description>System configuration module using Protobuf</description>
  <maintainer email="913982779@qq.com">winter</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>common</depend>
  <depend>ament_index_cpp</depend>
  <build_depend>libprotobuf-dev</build_depend>
  <exec_depend>libprotobuf-dev</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
